create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  email text not null,
  created_at timestamptz not null default now()
);

alter table public.users enable row level security;

create policy "Allow anonymous inserts"
on public.users
for insert
to anon
with check (true);